# Generated by Django 3.2 on 2021-04-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
